(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> decorator() takes exactly 1 argument (0 given)"
p3
sS'layer'
p4
S'/Users/adityagaykar/Dropbox/Development/MtechCSE/Sem1/SCE/Project/web2py/applications/edify/controllers/course.py'
p5
sS'code'
p6
S'import time\n\n@auth.requires_login\ndef index():\n\t#list the courses available for current year for registration\n\tcourses = []\n\trows = db(db.course).select()\n\tfor row in rows:\n\t\tcourses.append([row.name, row.faculty.first_name + " " +  row.faculty.last_name])\n\treturn locals()\n\n@auth.requires_login\ndef view():\n\tcourse_id = request.args(0)\n\tif course_id == None:\n\t\tresponse.flash("Invalid course")\n\t\tredirect("index")\n\treturn locals()\n\nresponse._vars=response._caller(view)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/adityagaykar/Dropbox/Development/MtechCSE/Sem1/SCE/Project/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/Users/adityagaykar/Dropbox/Development/MtechCSE/Sem1/SCE/Project/web2py/applications/edify/controllers/course.py", line 20, in <module>\n  File "/Users/adityagaykar/Dropbox/Development/MtechCSE/Sem1/SCE/Project/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\nTypeError: decorator() takes exactly 1 argument (0 given)\n'
p11
s.